apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: age-guesser-frontend
  template:
    metadata:
      labels:
        app: age-guesser-frontend
    spec:
      containers:
      - name: age-guesser-frontend
        image: DOCKERHUB_USERNAME/age-guesser-frontend:latest
        ports:
        - containerPort: 8080
